# Markdownlint configuration file
default: true,
line-length: false
<<<<<<< HEAD
no-multiple-blanks: 0
blanks-around-headers: false
blanks-around-lists: false
header-increment: false
=======
>>>>>>> upstream/TEMPLATE
no-duplicate-header:
    siblings_only: true
