lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
nf_core_version: 3.1.1
repository_type: pipeline
template:
  author: olgabot, itrujnara
  description: k-mer similarity analysis pipeline
  force: false
  is_nfcore: true
  name: kmermaid
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.0.0dev
