# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-kmermaid-0.1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::tqdm=4.43.0
  - conda-forge::clangxx_osx-64=11.1.0
  - conda-forge::s3fs=0.4.2
  - bioconda::sourmash=3.5.0
  - bioconda::samtools=1.10
  - bioconda::screed=1.0.4
  - bioconda::khmer=3.0.0a3
  - bioconda::pysam=0.16.0
  - anaconda::make=4.2.1
  - alabaster=0.7.12
  - fastp=0.20.0
  - fastqc=0.11.9
  - matplotlib=3.1.1 # don't upgrade, multiqc conflict
  - multiqc=1.8
  - numpy=1.17.5
  - pathos=0.2.5
  - pip=20.0.2
  - pytest=5.3.4
  - seqtk=1.3
  - ska=1.0
  - sphinx=2.3.1
  - jupyter=1.0.0
  - ripgrep=12.1.1
  - conda-forge::rust=1.48.0
  - rsync=3.2.3
  - pip:
    - bam2fasta==1.0.8
    - orpheum==1.0.4
